
# installing needed packages from previous device

if(!require("pacman")) install.packages("pacman")

x <- c("abind", "acepack", "ade4", "adehabitatHR", "adehabitatHS", 
"adehabitatLT", "adehabitatMA", "AICcmodavg", "animation", "aod", 
"ape", "arcdiagram", "askpass", "assertthat", "backports", "base64", 
"base64enc", "bayesdfa", "BayesLogit", "BBmisc", "bbmle", "BDgraph", 
"bdsmatrix", "BETS", "BH", "BiasedUrn", "bipartite", "bit", "bit64", 
"bitops", "blob", "brew", "broom", "callr", "car", "carData", 
"caret", "caTools", "cellranger", "checkmate", "chron", "CircStats", 
"circular", "classInt", "cli", "clipr", "clisymbols", "clusterGeneration", 
"coda", "colorspace", "colortools", "colourvalues", "combinat", 
"commonmark", "corpcor", "corrgram", "corrplot", "covr", "cowplot", 
"crayon", "crosstalk", "crul", "curl", "d3Network", "data.table", 
"DataExplorer", "date", "DBI", "dbplyr", "deldir", "dendextend", 
"DEoptimR", "Deriv", "desc", "deSolve", "devtools", "dichromat", 
"diffobj", "digest", "dismo", "doParallel", "dotCall64", "dplR", 
"dplyr", "DT", "dygraphs", "e1071", "ellipsis", "emdbook", "EnvStats", 
"epiR", "ergm", "evaluate", "exactextractr", "expm", "extrafont", 
"extrafontdb", "fansi", "farver", "fastmap", "fastmatch", "fdrtool", 
"fields", "filehash", "flexclust", "FNN", "fontBitstreamVera", 
"fontLiberation", "fontquiver", "forcats", "foreach", "forecast", 
"Formula", "fracdiff", "freetypeharfbuzz", "fs", "gam", "gbm", 
"gclus", "gdata", "gdtools", "generics", "geoaxe", "geobr", "geoR", 
"geosphere", "GGally", "gganimate", "ggforce", "ggfortify", "ggmap", 
"ggplot2", "ggplot2movies", "ggpubr", "ggraph", "ggrepel", "ggridges", 
"ggsci", "ggsignif", "ggsn", "gh", "GISTools", "git2r", "glasso", 
"glm2", "glmmfields", "glmnet", "glue", "gmodels", "goftest", 
"googlePolylines", "gower", "gplots", "graphlayouts", "gridExtra", 
"grnn", "gstat", "gsubfn", "gtable", "gtools", "GUILDS", "haven", 
"hexbin", "highr", "HKprocess", "Hmisc", "hms", "Hmsc", "hrbrthemes", 
"htm2txt", "htmltools", "htmlwidgets", "httpcode", "httpuv", 
"httr", "huge", "igraph", "ini", "INLA", "inline", "intervals", 
"ipred", "isoband", "iterators", "janitor", "jpeg", "jsonify", 
"jsonlite", "kernlab", "knitr", "labeling", "later", "lattice", 
"latticeExtra", "lava", "lavaan", "lazyeval", "leafem", "leaflet", 
"leaflet.providers", "leafpop", "leafsync", "LearnBayes", "legendMap", 
"lifecycle", "lme4", "lmtest", "loo", "lpSolve", "lubridate", 
"lwgeom", "magick", "magrittr", "manipulateWidget", "mapdata", 
"mapdeck", "mapproj", "maps", "maptools", "mapview", "markdown", 
"Matrix", "MatrixModels", "matrixStats", "maxlike", "maxnet", 
"mcmc", "MCMCpack", "memoise", "mgcv", "mime", "miniUI", "minqa", 
"miscset", "mitools", "mlr", "mnormt", "ModelMetrics", "modelr", 
"modeltools", "multcomp", "MuMIn", "munsell", "mvtnorm", "ndtv", 
"network", "networkD3", "networkDynamic", "nlme", "nloptr", "nortest", 
"numDeriv", "oai", "openssl", "openxlsx", "optimx", "orthopolynom", 
"packrat", "pacman", "parallelMap", "ParamHelpers", "pbapply", 
"pbivnorm", "pbkrtest", "pdist", "permute", "pgirmess", "phangorn", 
"phytools", "pillar", "pixmap", "pkgbuild", "pkgconfig", "pkgload", 
"plogr", "plotly", "plotrix", "plyr", "png", "poilog", "polspline", 
"polyclip", "polynom", "pracma", "praise", "prettyunits", "pROC", 
"processx", "prodlim", "profvis", "progress", "proj4", "promises", 
"proto", "ps", "psych", "purrr", "purrrlyr", "qap", "qgraph", 
"quadprog", "quantmod", "quantreg", "R.methodsS3", "R.oo", "R.utils", 
"R6", "randomcoloR", "RandomFields", "RandomFieldsUtils", "randomForest", 
"RANN", "rapidjsonr", "raster", "rasterVis", "rbison", "rcmdcheck", 
"RColorBrewer", "Rcpp", "RcppArmadillo", "RcppEigen", "RcppParallel", 
"RCurl", "readr", "readxl", "rebird", "recipes", "registry", 
"rematch", "rematch2", "remotes", "reprex", "reshape", "reshape2", 
"rex", "rgbif", "rgdal", "rgeos", "rgl", "RgoogleMaps", "ridigbio", 
"rio", "rJava", "rjson", "rlang", "rmarkdown", "rms", "RMySQL", 
"robustbase", "ROCR", "RODBC", "roxygen2", "rpart.plot", "rprojroot", 
"RSAGA", "RSQLite", "rstan", "rstantools", "RStoolbox", "rstudioapi", 
"Rtsne", "Rttf2pt1", "RUnit", "rversions", "rvertnet", "rvest", 
"sads", "sandwich", "satellite", "scales", "scatterplot3d", "seasonal", 
"selectr", "seriation", "sessioninfo", "sf", "sfheaders", "shape", 
"shapefiles", "shiny", "signal", "simecol", "sm", "sn", "sna", 
"snakecase", "SnowballC", "sourcetools", "sp", "spacetime", "spam", 
"SparseM", "spatialEco", "spatialwidget", "spatstat", "spatstat.data", 
"spatstat.utils", "spData", "spdep", "splancs", "splitstackshape", 
"spocc", "spThin", "sqldf", "SQUAREM", "StanHeaders", "stars", 
"statmod", "statnet.common", "stringi", "stringr", "survey", 
"svglite", "sys", "systemfonts", "tensor", "tergm", "testthat", 
"TH.data", "tibble", "tidygraph", "tidyr", "tidyselect", "tidyverse", 
"timeDate", "tinytex", "tkrplot", "tmap", "tmaptools", "tmvnsim", 
"triebeard", "truncnorm", "trust", "tseries", "tsna", "TSP", 
"TTR", "tweenr", "units", "unmarked", "urca", "urltools", "usdm", 
"usethis", "utf8", "uuid", "vctrs", "vdiffr", "vegan", "VGAM", 
"vioplot", "viridis", "viridisLite", "webshot", "wesanderson", 
"whisker", "wicket", "withr", "wordcloud", "wordcloud2", "x13binary", 
"xfun", "xgboost", "xlsx", "xlsxjars", "XML", "xml2", "xopen", 
"xtable", "xts", "yaImpute", "yaml", "zip", "zoo")

lapply(x, install.packages(x), character.only = T)

# load

# lapply(x, library, character.only=T)
