
# installing needed packages from previous device

if(!require("pacman")) install.packages("pacman")

x <- c("abind", "actuar", "ade4", "adehabitatHR", "adehabitatHS", 
"adehabitatLT", "adehabitatMA", "admisc", "afex", "akima", "alluvial", 
"ambient", "annotate", "AnnotationBustR", "AnnotationDbi", "antiword", 
"aod", "ape", "arkdb", "ash", "askpass", "assertthat", "automap", 
"backports", "base64enc", "BAT", "BayesFactor", "bayesm", "bayestestR", 
"bbmle", "bdsmatrix", "BH", "binman", "Biobase", "BiocGenerics", 
"BiocManager", "BiocVersion", "biomod2", "Biostrings", "bipartite", 
"biscale", "bit", "bit64", "bitops", "bivariatemaps", "bivarmap", 
"blob", "blogdown", "BMA", "bold", "bookdown", "brew", "bridgesampling", 
"brinla", "brio", "Brobdingnag", "broom", "bslib", "BWStest", 
"cachem", "callr", "cancensus", "car", "carData", "caret", "caTools", 
"cellranger", "censReg", "checkmate", "circlize", "CircStats", 
"classInt", "cli", "climateStability", "clipr", "clisymbols", 
"clusteval", "ClustGeo", "coda", "coefINLA", "collapse", "colorRamps", 
"colorspace", "comat", "commonmark", "compositions", "CompQuadForm", 
"conditionz", "conflicted", "conquer", "contentid", "contfrac", 
"CoordinateCleaner", "correlation", "corrplot", "countrycode", 
"covr", "cowplot", "cpp11", "crayon", "credentials", "crosstalk", 
"crul", "curl", "data.table", "DataCombine", "DataExplorer", 
"datawizard", "DBI", "dbplyr", "deldir", "dendextend", "DEoptimR", 
"Deriv", "desc", "DescTools", "deSolve", "devtools", "dfidx", 
"dfoptim", "DHARMa", "dichromat", "diffobj", "digest", "disaggregation", 
"dismo", "doParallel", "doRNG", "doSNOW", "dotCall64", "downloader", 
"dplR", "dplyr", "DT", "dtplyr", "duckdb", "e1071", "earth", 
"easyPubMed", "Ecdat", "Ecfun", "ecodist", "ecospat", "edgebundle", 
"effectsize", "ellipse", "ellipsis", "elliptic", "emdbook", "emmeans", 
"energy", "ENMeval", "ENMTML", "ENMTools", "EnvStats", "EpiDynamics", 
"eplusr", "epwshiftr", "EQL", "estimability", "evaluate", "evd", 
"Exact", "exactextractr", "expint", "expm", "extraDistr", "extrafont", 
"extrafontdb", "factoextra", "FactoMineR", "fansi", "farver", 
"fastcluster", "fasterize", "fastGHQuad", "fastICA", "fastmap", 
"fastmatch", "fBasics", "fda", "fds", "fGarch", "fields", "filehash", 
"fitdistrplus", "flashClust", "flexclust", "fmsb", "FNN", "fontawesome", 
"forcats", "foreach", "Formula", "fs", "fst", "fstcore", "future", 
"future.apply", "gam", "gamm4", "gap", "gap.datasets", "gapminder", 
"gargle", "gbm", "gdalUtils", "gdata", "gdistance", "gdtools", 
"generics", "GenomeInfoDb", "GenomeInfoDbData", "geojsonsf", 
"geometries", "geometry", "geomtextpath", "geosphere", "gert", 
"ggalt", "gganimate", "ggbump", "ggcorrplot", "ggdendro", "ggforce", 
"ggfortify", "ggfun", "gghighlight", "ggimage", "ggmap", "ggord", 
"ggplot2", "ggplotify", "ggpmisc", "ggpp", "ggpubr", "ggradar", 
"ggraph", "ggrepel", "ggridges", "ggsci", "ggsflabel", "ggside", 
"ggsignif", "ggsn", "ggspatial", "ggstatsplot", "ggtern", "ggthemes", 
"ggthemr", "ggVennDiagram", "gh", "gifski", "gitcreds", "gld", 
"glm2", "glmmML", "glmmTMB", "glmnet", "GlobalOptions", "globals", 
"glue", "gmodels", "gmp", "goftest", "googledrive", "googlePolylines", 
"googlesheets4", "gower", "gplots", "graphlayouts", "gravity", 
"gridExtra", "gridGraphics", "gsl", "gss", "gstat", "gsw", "gtable", 
"gtools", "GUILDS", "hardhat", "haven", "hdrcde", "here", "hexbin", 
"hexSticker", "highr", "hitandrun", "HKprocess", "Hmisc", "hms", 
"hrbrthemes", "HSAUR3", "htmlTable", "htmltools", "htmlwidgets", 
"httpcode", "httpuv", "httr", "hunspell", "huxtable", "hypergeo", 
"hypervolume", "ids", "igraph", "ini", "INLA", "inlatools", "INLAutils", 
"inline", "insight", "installr", "interp", "intervals", "ipred", 
"IRanges", "isoband", "iterators", "janitor", "jpeg", "jquerylib", 
"jsonify", "jsonlite", "kableExtra", "kdensity", "KEGGREST", 
"kernlab", "knitr", "ks", "kSamples", "labeling", "landscapemetrics", 
"landscapetools", "LaplacesDemon", "later", "latex2exp", "lattice", 
"latticeExtra", "lava", "lavaan", "lazyeval", "leafem", "leaflet", 
"leaflet.extras", "leaflet.opacity", "leaflet.providers", "leafpm", 
"leafpop", "leafsync", "leaps", "LearnBayes", "legendMap", "lhs", 
"lifecycle", "link2GI", "linprog", "listenv", "lme4", "lmerTest", 
"lmodel2", "lmom", "lmtest", "lobstr", "locfit", "logitnorm", 
"logspline", "loo", "lpSolve", "lsmetricsr", "lubridate", "lwgeom", 
"magic", "magick", "magrittr", "Manu", "mapdata", "mapedit", 
"mapproj", "maps", "maptools", "mapview", "markdown", "marmap", 
"mathjaxr", "Matrix", "MatrixModels", "matrixStats", "maxLik", 
"maxlike", "maxnet", "mc2d", "mclust", "mcmc", "MCMCpack", "mda", 
"memoise", "MEMSS", "merDeriv", "metaBMA", "metadat", "metafor", 
"metaplus", "mgc", "mgcv", "mime", "miniUI", "minqa", "misc3d", 
"miscTools", "mlmRev", "mlogit", "mnormt", "mobsim", "mockery", 
"ModelMetrics", "modelr", "modeltools", "motif", "multcomp", 
"multcompView", "multicool", "multiwayvcov", "MuMIn", "munsell", 
"mvtnorm", "nabor", "nakagami", "natserv", "ncdf4", "NCmisc", 
"network", "networkD3", "nlme", "nloptr", "nls2", "nngeo", "nonnest2", 
"nortest", "numbers", "numDeriv", "oai", "oaqc", "oce", "ocedata", 
"oneimpact", "openssl", "openxlsx", "optimx", "orthopolynom", 
"osrm", "paletteer", "palmerpenguins", "pals", "parallelly", 
"parameters", "patchwork", "pbapply", "pbivnorm", "pbkrtest", 
"pcaPP", "pdftools", "pdist", "performance", "permute", "pgirmess", 
"phangorn", "pheatmap", "philentropy", "phylolm", "piggyback", 
"pillar", "pixmap", "pkgbuild", "pkgconfig", "pkgload", "platexpress", 
"plm", "plogr", "plot3D", "plotly", "plotmo", "plotrix", "plyr", 
"PMCMRplus", "png", "poibin", "poilog", "polspline", "polyclip", 
"polynom", "poorman", "pracma", "praise", "PresenceAbsence", 
"prettymapr", "prettyunits", "prismatic", "pROC", "processx", 
"prodlim", "proftools", "progress", "progressr", "PROJ", "proj4", 
"promises", "proto", "proxy", "pryr", "ps", "psych", "psychrolib", 
"pubmedR", "purrr", "qgam", "qpdf", "quadprog", "quantreg", "R.methodsS3", 
"R.oo", "R.utils", "R6", "rainbow", "randomcoloR", "randomForest", 
"rangeModelMetadata", "ranger", "rapidjsonr", "rappdirs", "raster", 
"rasterVis", "ratelimitr", "rbibutils", "rbison", "rcdd", "rcmdcheck", 
"RColorBrewer", "Rcpp", "RcppArmadillo", "RcppEigen", "RcppGSL", 
"RcppParallel", "RcppProgress", "RcppTOML", "RcppZiggurat", "RCurl", 
"Rdpack", "readr", "readxl", "rebird", "recipes", "rematch", 
"rematch2", "remotes", "rentrez", "repr", "reprex", "reshape", 
"reshape2", "restez", "reticulate", "rex", "Rfast", "rgbif", 
"rgdal", "rgeoda", "rgeos", "rgl", "rglobi", "RgoogleMaps", "rgrass7", 
"ridigbio", "rio", "ritis", "rJava", "rjson", "RJSONIO", "rlang", 
"rmarkdown", "Rmpfr", "rms", "rnaturalearth", "rnaturalearthdata", 
"rncl", "RNetCDF", "rngtools", "robustbase", "RODBC", "rootSolve", 
"rosm", "rotl", "roxygen2", "Rphylip", "rprojroot", "rr2", "rrcov", 
"rredlist", "RSelenium", "RSQLite", "rstan", "rstantools", "rstatix", 
"RStoolbox", "rstudioapi", "Rtsne", "Rttf2pt1", "RVenn", "rversions", 
"rvertnet", "rvest", "rworldmap", "s2", "S4Vectors", "sads", 
"sampbias", "sandwich", "sass", "satellite", "scales", "scatterplot3d", 
"scico", "sdm", "segmented", "selectr", "semEff", "semver", "sensitivity", 
"seqinr", "servr", "sessioninfo", "sf", "sfheaders", "sfnetworks", 
"shape", "shiny", "showtext", "showtextdb", "signal", "SimInf", 
"skimr", "slam", "sn", "sna", "snakecase", "snow", "SnowballC", 
"snowfall", "solrium", "sourcetools", "sp", "spacetime", "spam", 
"SparseM", "sparseMVN", "spatialEco", "SpatialEpi", "SpatialKDE", 
"spatialRF", "spatstat", "spatstat.core", "spatstat.data", "spatstat.geom", 
"spatstat.linnet", "spatstat.random", "spatstat.sparse", "spatstat.utils", 
"spData", "spDataLarge", "spdep", "spelling", "splancs", "splitstackshape", 
"splus2R", "spocc", "spThin", "SQUAREM", "stabledist", "StanHeaders", 
"stars", "statmod", "statnet.common", "statsExpressions", "stplanr", 
"stringi", "stringr", "striprtf", "SuppDists", "survival", "svglite", 
"svMisc", "sys", "sysfonts", "systemfonts", "taxize", "TeachingDemos", 
"tensor", "tensorA", "terra", "testthat", "textreadr", "textshape", 
"textshaping", "TH.data", "tibble", "tidygraph", "tidyr", "tidyselect", 
"tidyverse", "tiff", "tigris", "timeDate", "timeSeries", "tinytex", 
"tis", "tmap", "tmaptools", "TMB", "tmbstan", "tmvnsim", "tricolore", 
"triebeard", "TSP", "ttutils", "tweenr", "tzdb", "units", "univariateML", 
"urltools", "usdm", "usethis", "utf8", "uuid", "V8", "vctrs", 
"vdiffr", "vegan", "venn", "VGAM", "viridis", "viridisLite", 
"vroom", "waldo", "WDI", "wdman", "wdpar", "webshot", "wellknown", 
"wesanderson", "whisker", "whoami", "widgetframe", "WikidataQueryServiceR", 
"WikidataR", "WikipediR", "wikitaxa", "withr", "wk", "wordcloud", 
"worrms", "WRS2", "xfun", "xlsx", "xlsxjars", "XML", "xml2", 
"xopen", "xtable", "xts", "XVector", "yaml", "yarrr", "yulab.utils", 
"zeallot", "zip", "zlibbioc", "zoo")

lapply(x, install.packages(x), character.only = T)

# load

# lapply(x, library, character.only=T)
