
# installing needed packages from previous device

if(!require("pacman")) install.packages("pacman")

x <- c("tibble", "abind", "acepack", "ade4", "adehabitatHR", 
       "adehabitatHS", "adehabitatLT", "adehabitatMA", "AICcmodavg", 
       "animation", "aod", "ape", "arcdiagram", "askpass", "assertthat", 
       "backports", "base64", "base64enc", "bayesdfa", "BayesLogit", 
       "BBmisc", "bbmle", "BDgraph", "bdsmatrix", "BH", "bipartite", 
       "bit", "bit64", "bitops", "blob", "brazilmaps", "brew", "broom", 
       "callr", "caret", "caTools", "cellranger", "checkmate", "CircStats", 
       "circular", "classInt", "cli", "clipr", "clisymbols", "clusterGeneration", 
       "coda", "colorspace", "colourvalues", "combinat", "commonmark", 
       "corpcor", "corrgram", "corrplot", "covr", "cowplot", "crayon", 
       "crosstalk", "crul", "curl", "d3Network", "data.table", "DataExplorer", 
       "DBI", "dbplyr", "deldir", "dendextend", "Deriv", "desc", "deSolve", 
       "devtools", "dichromat", "digest", "dismo", "doParallel", "dotCall64", 
       "dplR", "dplyr", "DT", "e1071", "ellipsis", "emdbook", "EnvStats", 
       "evaluate", "exactextractr", "expm", "fansi", "farver", "fastmap", 
       "fastmatch", "fdrtool", "fields", "filehash", "flexclust", "FNN", 
       "forcats", "foreach", "Formula", "fs", "gam", "gbm", "gclus", 
       "gdata", "gdtools", "generics", "geoaxe", "geobr", "geojsonsf", 
       "geoR", "geosphere", "ggforce", "ggfortify", "ggmap", "ggplot2", 
       "ggpubr", "ggraph", "ggrepel", "ggridges", "ggsci", "ggsignif", 
       "ggsn", "gh", "git2r", "glasso", "glm2", "glmmfields", "glmnet", 
       "glue", "gmodels", "goftest", "googlePolylines", "gower", "gplots", 
       "graphlayouts", "gridExtra", "gstat", "gtable", "gtools", "GUILDS", 
       "haven", "hexbin", "highr", "HKprocess", "Hmisc", "hms", "Hmsc", 
       "htmlTable", "htmltools", "htmlwidgets", "httpcode", "httpuv", 
       "httr", "huge", "igraph", "ini", "INLA", "inline", "intervals", 
       "ipred", "isoband", "iterators", "jpeg", "jsonify", "jsonlite", 
       "kernlab", "knitr", "labeling", "later", "lattice", "latticeExtra", 
       "lava", "lavaan", "lazyeval", "leafem", "leaflet", "leaflet.providers", 
       "leafpop", "leafsync", "LearnBayes", "legendMap", "lifecycle", 
       "lme4", "loo", "lubridate", "lwgeom", "magick", "magrittr", "manipulateWidget", 
       "mapdata", "mapdeck", "mapproj", "maps", "maptools", "mapview", 
       "markdown", "Matrix", "MatrixModels", "matrixStats", "maxlike", 
       "maxnet", "mcmc", "MCMCpack", "memoise", "mgcv", "mime", "miniUI", 
       "minqa", "mitools", "mlr", "mnormt", "ModelMetrics", "modelr", 
       "modeltools", "multcomp", "MuMIn", "munsell", "mvtnorm", "ndtv", 
       "network", "networkD3", "networkDynamic", "nlme", "nloptr", "nortest", 
       "numDeriv", "oai", "openssl", "openxlsx", "optimx", "orthopolynom", 
       "packrat", "pacman", "parallelMap", "ParamHelpers", "pbapply", 
       "pbivnorm", "pdist", "permute", "pgirmess", "phangorn", "phytools", 
       "pillar", "pixmap", "pkgbuild", "pkgconfig", "pkgload", "plogr", 
       "plotrix", "plyr", "png", "poilog", "polspline", "polyclip", 
       "polynom", "pracma", "praise", "prettyunits", "pROC", "processx", 
       "prodlim", "progress", "promises", "ps", "psych", "purrr", "qap", 
       "qgraph", "quadprog", "quantreg", "R.methodsS3", "R.oo", "R.utils", 
       "R6", "randomcoloR", "RandomFields", "RandomFieldsUtils", "randomForest", 
       "RANN", "rapidjsonr", "raster", "rasterVis", "rbison", "rcmdcheck", 
       "RColorBrewer", "Rcpp", "RcppArmadillo", "RcppEigen", "RCurl", 
       "readr", "readxl", "rebird", "recipes", "registry", "rematch", 
       "remotes", "reprex", "reshape", "reshape2", "rex", "rgbif", "rgdal", 
       "rgeos", "rgl", "RgoogleMaps", "ridigbio", "rJava", "rjson", 
       "rlang", "rmarkdown", "rms", "ROCR", "RODBC", "roxygen2", "rprojroot", 
       "RSAGA", "rstan", "rstantools", "RStoolbox", "rstudioapi", "Rtsne", 
       "RUnit", "rversions", "rvertnet", "rvest", "sads", "sandwich", 
       "satellite", "scales", "scatterplot3d", "selectr", "seriation", 
       "sessioninfo", "sf", "sfheaders", "shape", "shapefiles", "shiny", 
       "signal", "simecol", "sm", "sn", "sna", "SnowballC", "sourcetools", 
       "sp", "spacetime", "spam", "SparseM", "spatialEco", "SpatialPack", 
       "spatialwidget", "spatstat", "spatstat.data", "spatstat.utils", 
       "spData", "spDataLarge", "spdep", "splancs", "splitstackshape", 
       "spocc", "spThin", "SQUAREM", "StanHeaders", "stars", "statmod", 
       "statnet.common", "stringi", "stringr", "survey", "svglite", 
       "sys", "systemfonts", "tensor", "testthat", "TH.data", "tibble", 
       "tidygraph", "tidyr", "tidyselect", "tidyverse", "timeDate", 
       "tinytex", "tkrplot", "tmap", "tmaptools", "triebeard", "truncnorm", 
       "TSP", "tweenr", "units", "unmarked", "urltools", "usdm", "usethis", 
       "utf8", "uuid", "V8", "vctrs", "vegan", "VGAM", "vioplot", "viridis", 
       "viridisLite", "webshot", "wesanderson", "whisker", "wicket", 
       "withr", "wordcloud", "xfun", "xgboost", "xlsx", "xlsxjars", 
       "XML", "xml2", "xopen", "xtable", "xts", "yaImpute", "yaml", 
       "zip", "zoo")

lapply(x, install.packages(x), character.only = T)

# load

# lapply(x,library,character.only=T)
